title: Exocore
author: JamesLiao333
profile_link: https://twitter.com/jamesliao333
profile_pic: assets/images/james1.png

source: .
url: https://donnahorashi.netlify.app/
baseurl: ''
destination: ./_site


highlighter: rouge

gist:
  noscript: false

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

readme_index:
  enabled: true

repository: hot-domme/james-liao

sass:
    sass_dir: _sass

permalink: pretty

      
defaults:
  - scope:
      path: "" 
    values:
      layout: "default"
      date: "Jan 1 2000"
      
  - scope:
      path: "" 
      type: "library"
    values:
      document: "true"

feed:
  categories:
    - article
    - note
    - journal

collections:

  daily:
    output: true

  notes:
    output: true
    
  journal:
    output: true
    
  articles:
    output: true
  
  library:
    output: true
    
    
relative_links:
  enabled:     true
  collections: true
    
tag_page_layout: tag_page
tag_page_dir: tag

plugins:
- jekyll-optional-front-matter
- jekyll-readme-index
- jekyll-default-layout
- jekyll-titles-from-headings
- jekyll-relative-links
- jekyll-github-metadata
- jekyll-seo-tag
- html-proofer
- rubocop
- w3c_validators
- jekyll-last-modified-at
- jekyll-redirect-from
- jekyll-feed
- jekyll/tagging
- jekyll-wikilinks

